apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  MONGODB_USERNAME: dXNlcm5hbWU=  # Este é um exemplo codificado em base64 para "username"
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # Este é um exemplo codificado em base64 para "password"
