apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: cGd1c2Vy  # Este é um exemplo codificado em base64 para "pguser"
  POSTGRES_PASSWORD: cGdwYXNzd29yZA==  # Este é um exemplo codificado em base64 para "pgpassword"
