apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: {{environment}}
spec:
  selector:
    app: example-app
    tier: web
  type: NodePort
  ports:
    - name: http-web-svc
      protocol: TCP
      port: 8080
      targetPort: web-server
