apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0dXNlcg==  # Codificado em base64 para "rabbituser"
  RABBITMQ_DEFAULT_PASS: cmFiYml0cGFzc3dvcmQ=  # Codificado em base64 para "rabbitpassword"
